### ISSUE TITLE
Few things

### ISSUE THREAD

**Issue by davit-b** [VIEWVIEWVIEW/lume-tailwind-daisyui-typography#1]
This is the best. Thanks for creating this, it helped me immensely. 

Few things I've noticed in the repo that can be cleaned up - the scripts of MacOS and Linux have extensions `.exe`

and there is no `<link rel="stylesheet" href="../tailwind.css" />` in any parent html, so it's hard to see where this would get connected in a deno app that doesn't run Lume. 

I'll open up my repo soon that uses this method for generating the `tailwind.css`

**Comment by VIEWVIEWVIEW** [comment]
Glad that it helped!

I won't touch this project, as it was just an explainer for https://github.com/saadeghi/daisyui/issues/932. However, if you are *really* bothered by the file extensions, you can create a PR.

The ``tailwind.css`` is referenced in the main layout for this project. 
https://github.com/VIEWVIEWVIEW/lume-tailwind-daisyui-typography/blob/90f47668e235f04130407a77f362f5de07251bd1/src/_includes/layouts/main.njk#L11

**Comment by davit-b** [comment]
Ahh! I missed it because I didn't ctrl-f the project, and didn't think to check nunjuks.

My repo example uses only Tailwindcss and DaisyUI. I'll ping when it's public. 

Thanks ago. I really found your explanation a lifesaver and I learned alot :)
